### ISSUE TITLE
cannot build image

### ISSUE THREAD

**Issue by guoloveguo** [picadoh/boots#1]
Hi Hugo,

Thanks for providing this sample code. it is very helpful! 
I downloaded the code and run: docker build -t picadoh/cassandra . 
However I see below, could you please take a look? Thanks a lot.

Step 5/14 : ENV VERSION 3.7
 ---> Using cache
 ---> 9e8ae12ceff3
Step 6/14 : RUN curl $MIRROR/cassandra/$VERSION/apache-cassandra-$VERSION-bin.tar.gz | tar -xzf - -C /opt     && mv /opt/apache-cassandra-$VERSION /opt/cassandra     && mkdir -p /tmp/cassandra
 ---> Running in 2c5be7a103b8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   243  100   243    0     0   1497      0 --:--:-- --:--:-- --:--:--  1500

**_gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now_**
The command '/bin/sh -c curl $MIRROR/cassandra/$VERSION/apache-cassandra-$VERSION-bin.tar.gz | tar -xzf - -C /opt     && mv /opt/apache-cassandra-$VERSION /opt/cassandra     && mkdir -p /tmp/cassandra' returned a non-zero code: 2

Best,
Shaohui

**Comment by picadoh** [comment]
Hello @sjphiChina. Thanks for reporting and sorry for the late reply. It was using an older version of the Cassandra package that was not present in the mirror anymore. Changed to 3.11.1 (the most recent one). Should be working now. 

Also, updated the boots Dockerfile to build from Docker itself instead of requiring a pre-installation of Maven and Java.

Steps for the full example:

1. **docker build -t picadoh/cassandra cassandra/.** _(or just . if running from cassandra folder)_
2. **docker run -d --name cassandra -p 9042:9042 picadoh/cassandra**
3. **docker build -t picadoh/boots**
4. **docker run --name boots --link cassandra:db -p 8080:8080 picadoh/boots**
